# Generated by Django 3.2.3 on 2021-07-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_delete_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpentMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_money', models.IntegerField(default=0)),
                ('comments', models.TextField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='add_money',
        ),
    ]
