# Generated by Django 3.2.3 on 2021-07-05 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_auto_20210703_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='spentmoney',
            name='time_input',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
