# Generated by Django 3.2.3 on 2021-07-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0008_auto_20210706_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spentmoney',
            name='add_money',
            field=models.FloatField(default=0),
        ),
    ]
