# Generated by Django 3.2.3 on 2021-07-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user',
        ),
    ]
