# Generated by Django 3.2.3 on 2021-07-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0014_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='name_user',
        ),
    ]
