# Generated by Django 3.2.3 on 2021-07-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0015_rename_name_user_name_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name_user',
        ),
        migrations.AddField(
            model_name='person3',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
