# Generated by Django 3.2.3 on 2021-07-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0016_auto_20210709_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person3',
        ),
    ]
