# Generated by Django 3.2.3 on 2021-07-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0017_delete_person3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18)),
                ('credit_card_number', models.CharField(max_length=90)),
            ],
        ),
    ]
