# Generated by Django 3.2.3 on 2021-07-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0019_auto_20210710_1652'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
