# Generated by Django 3.2.3 on 2021-07-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0021_auto_20210725_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='Address'),
            preserve_default=False,
        ),
    ]
