# Generated by Django 3.2.3 on 2021-07-25 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0023_cat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
    ]
