# Generated by Django 3.2.3 on 2021-08-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0027_income_time_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='time_input',
        ),
    ]
