# Generated by Django 3.2.3 on 2021-08-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0027_income_time_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='set_day',
            field=models.IntegerField(default=1, max_length=31),
        ),
    ]
