# Generated by Django 3.2.3 on 2021-08-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0029_alter_client_set_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person3',
        ),
    ]
