# Generated by Django 3.2.3 on 2021-09-28 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0031_hero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
